In [1]:
print('set up already !')

set up already !


In [2]:
#mengimport module numpy.py
import numpy as np

In [3]:
#beberapa method yg dimiliki oleh numpy
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

## Membuat array

In [23]:
#membuat sebuah array

A = np.array([2, 1, 4, 5, 5, 7, 4, 4, 2, 1])
B = np.array([
    [2, 1, 3, 4],
    [3, 1, 1, 3],
    [2, 2, 2, 8], 
    [3, 4, 2, 7],
    [0, 1, 3, 2]
])

C = np.arange(1, 16, 3)
list_ = [a**2 for a in range(5)]
D = np.fromiter(list_, dtype=np.int64)

print(A)
print()
print(B)
print()
print(C)
print()
print(D)

[2 1 4 5 5 7 4 4 2 1]

[[2 1 3 4]
 [3 1 1 3]
 [2 2 2 8]
 [3 4 2 7]
 [0 1 3 2]]

[ 1  4  7 10 13]

[ 0  1  4  9 16]


In [21]:
X = np.linspace(2, 10, 2, dtype = np.float64)
print(X)
print()
Y = np.ones([2, 3], dtype=np.float32)
print(Y)
print()
Z = np.zeros([3, 3], dtype=np.float32)
print(Z)

AB = np.identity(3)
print(AB)

#membuat array full
five = np.full([4, 1], 5)
print(five)

[ 2. 10.]

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5]
 [5]
 [5]
 [5]]


In [24]:
#sifat array
print(A.shape)
print(B.shape)
print(B.ndim)

(10,)
(5, 4)
2


## Akses dan slicing array

In [25]:
#mengakses array numpy sama dengan list
print(A[1:])
print(A[-1])
print(A[:-1])

[1 4 5 5 7 4 4 2 1]
1
[2 1 4 5 5 7 4 4 2]


In [27]:
B = np.array([
    [2, 1, 3, 4],
    [3, 1, 1, 3],
    [2, 2, 2, 8], 
    [3, 4, 2, 7],
    [0, 1, 3, 2]
])

print(B)
print(B[1])
print()
print(B[1, 1])
print()
print(B[1:3, -1])
print()
print('mengambil baris kolom ketiga saja : {}'.format(B[:, 2]))

[[2 1 3 4]
 [3 1 1 3]
 [2 2 2 8]
 [3 4 2 7]
 [0 1 3 2]]
[3 1 1 3]

1

[3 8]

mengambil baris kolom ketiga saja : [3 1 2 2 3]


In [9]:
#slicing dengan boolean
greather_one = B > 1
print(B[greather_one])


[2 3 4 3 3 2 2 2 8 3 4 2 7 3 2]


## manipulasi array

In [28]:
#operasi aritmatika pada array
# operasi tiap element(element wise)
print(A + 1)
print()
print(B * 2)
print()
print(B.T)

[3 2 5 6 6 8 5 5 3 2]

[[ 4  2  6  8]
 [ 6  2  2  6]
 [ 4  4  4 16]
 [ 6  8  4 14]
 [ 0  2  6  4]]

[[2 3 2 3 0]
 [1 1 2 4 1]
 [3 1 2 2 3]
 [4 3 8 7 2]]


In [29]:
#tipe angka pada array 
#np.int64 atau np.float64

A = np.array(A, dtype=np.float64)
print(A)
B = np.array(B, dtype=np.float64)
print(B)

[2. 1. 4. 5. 5. 7. 4. 4. 2. 1.]
[[2. 1. 3. 4.]
 [3. 1. 1. 3.]
 [2. 2. 2. 8.]
 [3. 4. 2. 7.]
 [0. 1. 3. 2.]]


In [30]:
#menambahkan elemen kedalam array

G = np.copy(A)
print(G)
G = np.append(G, [20, 40])
print(G)

[2. 1. 4. 5. 5. 7. 4. 4. 2. 1.]
[ 2.  1.  4.  5.  5.  7.  4.  4.  2.  1. 20. 40.]


In [31]:
#merubah ukuran array
H = np.reshape(G, (3, 4))
print(H)

#menambah dimensi dengan expand dim
J = np.copy(A)
J = np.expand_dims(J, axis=1)
print(J)
print(J.shape)

[[ 2.  1.  4.  5.]
 [ 5.  7.  4.  4.]
 [ 2.  1. 20. 40.]]
[[2.]
 [1.]
 [4.]
 [5.]
 [5.]
 [7.]
 [4.]
 [4.]
 [2.]
 [1.]]
(10, 1)


In [32]:
#menambah kolom baru dengan array[100, 99, 101]
new_col = np.array([100, 99, 101]).reshape(3, 1)
H = np.append(H, new_col, axis=1) #Axis 1 artinya merujuk pada colomn jika axis = 0 merujuk pada baris
print(H)

[[  2.   1.   4.   5. 100.]
 [  5.   7.   4.   4.  99.]
 [  2.   1.  20.  40. 101.]]


In [33]:
#np.unique
K = np.copy(A)
print(A)
print(np.unique(K))

[2. 1. 4. 5. 5. 7. 4. 4. 2. 1.]
[1. 2. 4. 5. 7.]


In [34]:
l = np.copy(A).reshape(2, 5)
print(l)
print(np.unique(l))
print(np.unique(l, axis=0))
print(np.unique(l, axis = 1))

#axis=0 merujuk pada baris yg unik,  axis=1 merujuk pada colom yang unik

[[2. 1. 4. 5. 5.]
 [7. 4. 4. 2. 1.]]
[1. 2. 4. 5. 7.]
[[2. 1. 4. 5. 5.]
 [7. 4. 4. 2. 1.]]
[[1. 2. 4. 5. 5.]
 [4. 7. 4. 1. 2.]]


In [2]:
import numpy as np

In [4]:
#Matriks manipulasi numpy
M = np.arange(6).reshape(2, 3)
N = np.arange(4, 10).reshape(2, 3)
print(M)
print()
print(N)

#menambah matriks
print(np.add(M, N))

#perkalian matriks
print(np.matmul(M, np.reshape(N, (3, 2))))
print(M @ np.reshape(N, (3, 2)))

[[0 1 2]
 [3 4 5]]

[[4 5 6]
 [7 8 9]]
[[ 4  6  8]
 [10 12 14]]
[[22 25]
 [76 88]]
[[22 25]
 [76 88]]


In [19]:
#pelajari np.linalg modul untuk lebih lanjut
#perkalian matrix

A = np.arange(1, 5).reshape(2, 2)
B = np.arange(5, 9).reshape(2, 2)
print(A)
print(B)
print(np.dot(A, B))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [20]:
A = np.array([
    [2, 3],
    [1, 2]
])

B = np.array([1, 2]).reshape(2, 1)

print(np.dot(A, B))

[[8]
 [5]]


In [21]:
#perkalian vektor
#dot product

a = np.arange(1, 5)
b = np.arange(1, 5)
print(a, b)
print(np.dot(a, b))
print(a @ b)

[1 2 3 4] [1 2 3 4]
30
30


In [22]:
#cross product
a = a.reshape(2,2)
b = b.reshape(2,2)
print(np.cross(a, b))

[0 0]


In [23]:
#determinan matriks
from numpy import linalg as la

a = np.array([
    [2, 3, 2],
    [9, 2, 3],
    [1, 2, 7]
])
print(la.det(a))

-131.99999999999997


In [24]:
#ivers matriks
a = np.array([
    [5, 2],
    [3, 2]
])

print(la.det(a))
print(la.inv(a))



3.999999999999999
[[ 0.5  -0.5 ]
 [-0.75  1.25]]


## basic statistic

In [25]:
#numpy summary statistic
#mean

A = np.array([1, 3, 5, 7, 9])
B = np.array([
    [2, 3, 4],
    [3, 4, 2],
    [6, 2, 4]
])

print(A.mean())
print(B.mean())
print(B.mean(axis=1))

5.0
3.3333333333333335
[3. 3. 4.]


In [41]:
#median
A = np.array([1, 3, 5, 7, 9])
print(np.median(A))

B = np.array([
    [2, 3, 4],
    [3, 4, 2],
    [6, 2, 4]
])
print(np.median(B, axis=1))

5.0
[3. 3. 4.]


In [42]:
#standar deviation
A.std()

2.8284271247461903

In [28]:
#sum
print(A.sum())
print(B.sum(axis=0)) # axis 0 merujuk pada kolom
print(B.sum(axis=1)) #axis 1 merukuk pada baris

25
[11  9 10]
[ 9  9 12]


# random

In [3]:
a = np.random.rand(2, 3)
a

array([[0.21499066, 0.2037752 , 0.9141236 ],
       [0.07016582, 0.13384128, 0.52510115]])

In [5]:
# random state
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])

## numpy exercises

In [4]:
import math

print(math.floor(3/2))

1
